[package]
name = "telemetry"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear"}
telemetry-io = { path = "../io" }

[build-dependencies]
gear-ext-builder = { git = "https://github.com/nikvolf/cargo-gtest" }
